[project]
name = "pytorchlearning"
version = "0.1.0"
description = "pytorch playground"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "notebook>=7.4.7",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
]
